export const sidebarLinks=[
    {
        label:'Home',
        href:'#'
    },
    {
        label:'Orders',
        href:'#'
    },    
    {
        label:'Products',
        href:'#'
    },    
    {
        label:'Delivery',
        href:'#'
    },    
    {
        label:'Marketing',
        href:'#'
    },    {
        label:'Analytics',
        href:'#'
    },    
    {
        label:'Payments',
        href:'#'
    },    
    {
        label:'Tools',
        href:'#'
    },    
    {
        label:'Discounts',
        href:'#'
    },    
    {
        label:'Audience',
        href:'#'
    },    
    {
        label:'Appearance',
        href:'#'
    },
    {
        label:'Plugins',
        href:'#'
    },
]